const List<Map<String, dynamic>> cities = [
  {"text": "Abidjan, Ivory Coast", "value": "Abidjan"},
  {"text": "Abu Dhabi, United Arab Emirates", "value": "Abu Dhabi"},
  {"text": "Abuja, Nigeria", "value": "Abuja"},
  {"text": "Accra, Ghana", "value": "Accra"},
  {"text": "Addis Ababa, Ethiopia", "value": "Addis Ababa"},
  {"text": "Ahmedabad, India", "value": "Ahmedabad"},
  {"text": "Aleppo, Syria", "value": "Aleppo"},
  {"text": "Alexandria, Egypt", "value": "Alexandria"},
  {"text": "Algiers, Algeria", "value": "Algiers"},
  {"text": "Almaty, Kazakhstan", "value": "Almaty"},
  {"text": "Amman, Jordan", "value": "Amman"},
  {"text": "Amsterdam, Netherlands", "value": "Amsterdam"},
  {"text": "Anchorage, United States", "value": "Anchorage"},
  {"text": "Andorra la Vella, Andorra", "value": "Andorra la Vella"},
  {"text": "Ankara, Turkey", "value": "Ankara"},
  {"text": "Antananarivo, Madagascar", "value": "Antananarivo"},
  {"text": "Apia, Samoa", "value": "Apia"},
  {"text": "Arnold, United States", "value": "Arnold"},
  {"text": "Ashgabat, Turkmenistan", "value": "Ashgabat"},
  {"text": "Asmara, Eritrea", "value": "Asmara"},
  {"text": "Asuncion, Paraguay", "value": "Asuncion"},
  {"text": "Athens, Greece", "value": "Athens"},
  {"text": "Auckland, New Zealand", "value": "Auckland"},
  {"text": "Avarua, Cook Islands", "value": "Avarua"},
  {"text": "Baghdad, Iraq", "value": "Baghdad"},
  {"text": "Baku, Azerbaijan", "value": "Baku"},
  {"text": "Bamako, Mali", "value": "Bamako"},
  {"text": "Banda Aceh, Indonesia", "value": "Banda Aceh"},
  {"text": "Bandar Seri Begawan, Brunei", "value": "Bandar Seri Begawan"},
  {"text": "Bandung, Indonesia", "value": "Bandung"},
  {"text": "Bangkok, Thailand", "value": "Bangkok"},
  {"text": "Bangui, Central African Republic", "value": "Bangui"},
  {"text": "Banjul, Gambia", "value": "Banjul"},
  {"text": "Barcelona, Spain", "value": "Barcelona"},
  {"text": "Barranquilla, Colombia", "value": "Barranquilla"},
  {"text": "Basrah, Iraq", "value": "Basrah"},
  {"text": "Basse-Terre, Guadeloupe", "value": "Basse-Terre"},
  {"text": "Basseterre, Saint Kitts and Nevis", "value": "Basseterre"},
  {"text": "Beijing, China", "value": "Beijing"},
  {"text": "Beirut, Lebanon", "value": "Beirut"},
  {"text": "Bekasi, Indonesia", "value": "Bekasi"},
  {"text": "Belem, Brazil", "value": "Belem"},
  {"text": "Belgrade, Serbia", "value": "Belgrade"},
  {"text": "Belmopan, Belize", "value": "Belmopan"},
  {"text": "Belo Horizonte, Brazil", "value": "Belo Horizonte"},
  {"text": "Bengaluru, India", "value": "Bengaluru"},
  {"text": "Berlin, Germany", "value": "Berlin"},
  {"text": "Bern, Switzerland", "value": "Bern"},
  {"text": "Bishkek, Kyrgyzstan", "value": "Bishkek"},
  {"text": "Bissau, Guinea-Bissau", "value": "Bissau"},
  {"text": "Bogota, Colombia", "value": "Bogota"},
  {"text": "Brasilia, Brazil", "value": "Brasilia"},
  {"text": "Bratislava, Slovakia", "value": "Bratislava"},
  {"text": "Brazzaville, Republic of the Congo", "value": "Brazzaville"},
  {"text": "Bridgetown, Barbados", "value": "Bridgetown"},
  {"text": "Brisbane, Australia", "value": "Brisbane"},
  {"text": "Brussels, Belgium", "value": "Brussels"},
  {"text": "Bucharest, Romania", "value": "Bucharest"},
  {"text": "Budapest, Hungary", "value": "Budapest"},
  {"text": "Buenos Aires, Argentina", "value": "Buenos Aires"},
  {"text": "Bujumbura, Burundi", "value": "Bujumbura"},
  {"text": "Bursa, Turkey", "value": "Bursa"},
  {"text": "Busan, South Korea", "value": "Busan"},
  {"text": "Cairo, Egypt", "value": "Cairo"},
  {"text": "Cali, Colombia", "value": "Cali"},
  {"text": "Caloocan, Philippines", "value": "Caloocan"},
  {"text": "Camayenne, Guinea", "value": "Camayenne"},
  {"text": "Canberra, Australia", "value": "Canberra"},
  {"text": "Cape Town, South Africa", "value": "Cape Town"},
  {"text": "Caracas, Venezuela", "value": "Caracas"},
  {"text": "Casablanca, Morocco", "value": "Casablanca"},
  {"text": "Castries, Saint Lucia", "value": "Castries"},
  {"text": "Cayenne, French Guiana", "value": "Cayenne"},
  {"text": "Charlotte Amalie, U.S. Virgin Islands", "value": "Charlotte Amalie"},
  {"text": "Chengdu, China", "value": "Chengdu"},
  {"text": "Chennai, India", "value": "Chennai"},
  {"text": "Chicago, United States", "value": "Chicago"},
  {"text": "Chisinau, Moldova", "value": "Chisinau"},
  {"text": "Chittagong, Bangladesh", "value": "Chittagong"},
  {"text": "Chongqing, China", "value": "Chongqing"},
  {"text": "Colombo, Sri Lanka", "value": "Colombo"},
  {"text": "Conakry, Guinea", "value": "Conakry"},
  {"text": "Copenhagen, Denmark", "value": "Copenhagen"},
  {"text": "Cordoba, Argentina", "value": "Cordoba"},
  {"text": "Curitiba, Brazil", "value": "Curitiba"},
  {"text": "Daegu, South Korea", "value": "Daegu"},
  {"text": "Daejeon, South Korea", "value": "Daejeon"},
  {"text": "Dakar, Senegal", "value": "Dakar"},
  {"text": "Dallas, United States", "value": "Dallas"},
  {"text": "Damascus, Syria", "value": "Damascus"},
  {"text": "Dar es Salaam, Tanzania", "value": "Dar es Salaam"},
  {"text": "Delhi, India", "value": "Delhi"},
  {"text": "Denver, United States", "value": "Denver"},
  {"text": "Dhaka, Bangladesh", "value": "Dhaka"},
  {"text": "Dili, Timor Leste", "value": "Dili"},
  {"text": "Djibouti, Djibouti", "value": "Djibouti"},
  {"text": "Dodoma, Tanzania", "value": "Dodoma"},
  {"text": "Doha, Qatar", "value": "Doha"},
  {"text": "Dongguan, China", "value": "Dongguan"},
  {"text": "Douala, Cameroon", "value": "Douala"},
  {"text": "Douglas, Isle of Man", "value": "Douglas"},
  {"text": "Dubai, United Arab Emirates", "value": "Dubai"},
  {"text": "Dublin, Ireland", "value": "Dublin"},
  {"text": "Durban, South Africa", "value": "Durban"},
  {"text": "Dushanbe, Tajikistan", "value": "Dushanbe"},
  {"text": "Faisalabad, Pakistan", "value": "Faisalabad"},
  {"text": "Fort-de-France, Martinique", "value": "Fort-de-France"},
  {"text": "Fortaleza, Brazil", "value": "Fortaleza"},
  {"text": "Freetown, Sierra Leone", "value": "Freetown"},
  {"text": "Fukuoka, Japan", "value": "Fukuoka"},
  {"text": "Funafuti, Tuvalu", "value": "Funafuti"},
  {"text": "Gaborone, Botswana", "value": "Gaborone"},
  {"text": "George Town, Malaysia", "value": "George Town"},
  {"text": "Georgetown, Guyana", "value": "Georgetown"},
  {"text": "Gibraltar, Gibraltar", "value": "Gibraltar"},
  {"text": "Gitega, Burundi", "value": "Gitega"},
  {"text": "Giza, Egypt", "value": "Giza"},
  {"text": "Guadalajara, Mexico", "value": "Guadalajara"},
  {"text": "Guangzhou, China", "value": "Guangzhou"},
  {"text": "Guatemala City, Guatemala", "value": "Guatemala City"},
  {"text": "Guayaquil, Ecuador", "value": "Guayaquil"},
  {"text": "Gujranwala, Pakistan", "value": "Gujranwala"},
  {"text": "Gustavia, Saint Barthelemy", "value": "Gustavia"},
  {"text": "Gwangju, South Korea", "value": "Gwangju"},
  {"text": "Hamburg, Germany", "value": "Hamburg"},
  {"text": "Hanoi, Vietnam", "value": "Hanoi"},
  {"text": "Harare, Zimbabwe", "value": "Harare"},
  {"text": "Havana, Cuba", "value": "Havana"},
  {"text": "Helsinki, Finland", "value": "Helsinki"},
  {"text": "Ho Chi Minh City, Vietnam", "value": "Ho Chi Minh City"},
  {"text": "Hong Kong, Hong Kong", "value": "Hong Kong"},
  {"text": "Honiara, Solomon Islands", "value": "Honiara"},
  {"text": "Honolulu, United States", "value": "Honolulu"},
  {"text": "Houston, United States", "value": "Houston"},
  {"text": "Hyderabad, India", "value": "Hyderabad"},
  {"text": "Hyderabad, Pakistan", "value": "Hyderabad"},
  {"text": "Ibadan, Nigeria", "value": "Ibadan"},
  {"text": "Incheon, South Korea", "value": "Incheon"},
  {"text": "Isfahan, Iran", "value": "Isfahan"},
  {"text": "Islamabad, Pakistan", "value": "Islamabad"},
  {"text": "Istanbul, Turkey", "value": "Istanbul"},
  {"text": "Izmir, Turkey", "value": "Izmir"},
  {"text": "Jaipur, India", "value": "Jaipur"},
  {"text": "Jakarta, Indonesia", "value": "Jakarta"},
  {"text": "Jeddah, Saudi Arabia", "value": "Jeddah"},
  {"text": "Jerusalem, Israel", "value": "Jerusalem"},
  {"text": "Johannesburg, South Africa", "value": "Johannesburg"},
  {"text": "Juarez, Mexico", "value": "Juarez"},
  {"text": "Juba, South Sudan", "value": "Juba"},
  {"text": "Kabul, Afghanistan", "value": "Kabul"},
  {"text": "Kaduna, Nigeria", "value": "Kaduna"},
  {"text": "Kampala, Uganda", "value": "Kampala"},
  {"text": "Kano, Nigeria", "value": "Kano"},
  {"text": "Kanpur, India", "value": "Kanpur"},
  {"text": "Kaohsiung, Taiwan", "value": "Kaohsiung"},
  {"text": "Karachi, Pakistan", "value": "Karachi"},
  {"text": "Karaj, Iran", "value": "Karaj"},
  {"text": "Kathmandu, Nepal", "value": "Kathmandu"},
  {"text": "Kawasaki, Japan", "value": "Kawasaki"},
  {"text": "Kharkiv, Ukraine", "value": "Kharkiv"},
  {"text": "Khartoum, Sudan", "value": "Khartoum"},
  {"text": "Khulna, Bangladesh", "value": "Khulna"},
  {"text": "Kigali, Rwanda", "value": "Kigali"},
  {"text": "Kingsburg, United States", "value": "Kingsburg"},
  {"text": "Kingston, Jamaica", "value": "Kingston"},
  {"text": "Kingstown, Saint Vincent and the Grenadines", "value": "Kingstown"},
  {"text": "Kinshasa, Democratic Republic of the Congo", "value": "Kinshasa"},
  {"text": "Kobe, Japan", "value": "Kobe"},
  {"text": "Kolkata, India", "value": "Kolkata"},
  {"text": "Kota Bharu, Malaysia", "value": "Kota Bharu"},
  {"text": "Kowloon, Hong Kong", "value": "Kowloon"},
  {"text": "Kuala Lumpur, Malaysia", "value": "Kuala Lumpur"},
  {"text": "Kumasi, Ghana", "value": "Kumasi"},
  {"text": "Kuwait, Kuwait", "value": "Kuwait"},
  {"text": "Kyiv, Ukraine", "value": "Kyiv"},
  {"text": "Kyoto, Japan", "value": "Kyoto"},
  {"text": "La Paz, Bolivia", "value": "La Paz"},
  {"text": "Lagos, Nigeria", "value": "Lagos"},
  {"text": "Lahore, Pakistan", "value": "Lahore"},
  {"text": "Libreville, Gabon", "value": "Libreville"},
  {"text": "Lilongwe, Malawi", "value": "Lilongwe"},
  {"text": "Lima, Peru", "value": "Lima"},
  {"text": "Lisbon, Portugal", "value": "Lisbon"},
  {"text": "Ljubljana, Slovenia", "value": "Ljubljana"},
  {"text": "Lome, Togo", "value": "Lome"},
  {"text": "London, United Kingdom", "value": "London"},
  {"text": "Los Angeles, United States", "value": "Los Angeles"},
  {"text": "Luanda, Angola", "value": "Luanda"},
  {"text": "Lubumbashi, Democratic Republic of the Congo", "value": "Lubumbashi"},
  {"text": "Lusaka, Zambia", "value": "Lusaka"},
  {"text": "Luxembourg, Luxembourg", "value": "Luxembourg"},
  {"text": "Macau, Macao", "value": "Macau"},
  {"text": "Madrid, Spain", "value": "Madrid"},
  {"text": "Majuro, Marshall Islands", "value": "Majuro"},
  {"text": "Makassar, Indonesia", "value": "Makassar"},
  {"text": "Malabo, Equatorial Guinea", "value": "Malabo"},
  {"text": "Male, Maldives", "value": "Male"},
  {"text": "Mamoudzou, Mayotte", "value": "Mamoudzou"},
  {"text": "Managua, Nicaragua", "value": "Managua"},
  {"text": "Manama, Bahrain", "value": "Manama"},
  {"text": "Manaus, Brazil", "value": "Manaus"},
  {"text": "Manila, Philippines", "value": "Manila"},
  {"text": "Maputo, Mozambique", "value": "Maputo"},
  {"text": "Maracaibo, Venezuela", "value": "Maracaibo"},
  {"text": "Maracay, Venezuela", "value": "Maracay"},
  {"text": "Mariehamn, Aland Islands", "value": "Mariehamn"},
  {"text": "Marigot, Saint Martin", "value": "Marigot"},
  {"text": "Maseru, Lesotho", "value": "Maseru"},
  {"text": "Mashhad, Iran", "value": "Mashhad"},
  {"text": "Mbabane, Eswatini", "value": "Mbabane"},
  {"text": "Mecca, Saudi Arabia", "value": "Mecca"},
  {"text": "Medan, Indonesia", "value": "Medan"},
  {"text": "Medellin, Colombia", "value": "Medellin"},
  {"text": "Medina, Saudi Arabia", "value": "Medina"},
  {"text": "Melbourne, Australia", "value": "Melbourne"},
  {"text": "Mexico City, Mexico", "value": "Mexico City"},
  {"text": "Miami, United States", "value": "Miami"},
  {"text": "Minsk, Belarus", "value": "Minsk"},
  {"text": "Mogadishu, Somalia", "value": "Mogadishu"},
  {"text": "Monaco, Monaco", "value": "Monaco"},
  {"text": "Monrovia, Liberia", "value": "Monrovia"},
  {"text": "Montevideo, Uruguay", "value": "Montevideo"},
  {"text": "Montreal, Canada", "value": "Montreal"},
  {"text": "Moroni, Comoros", "value": "Moroni"},
  {"text": "Moscow, Russia", "value": "Moscow"},
  {"text": "Mosul, Iraq", "value": "Mosul"},
  {"text": "Multan, Pakistan", "value": "Multan"},
  {"text": "Mumbai, India", "value": "Mumbai"},
  {"text": "Muscat, Oman", "value": "Muscat"},
  {"text": "N'Djamena, Chad", "value": "N'Djamena"},
  {"text": "Nagoya, Japan", "value": "Nagoya"},
  {"text": "Nairobi, Kenya", "value": "Nairobi"},
  {"text": "Nanchong, China", "value": "Nanchong"},
  {"text": "Nanjing, China", "value": "Nanjing"},
  {"text": "Nassau, Bahamas", "value": "Nassau"},
  {"text": "Nay Pyi Taw, Myanmar", "value": "Nay Pyi Taw"},
  {"text": "New York, United States", "value": "New York"},
  {"text": "Niamey, Niger", "value": "Niamey"},
  {"text": "Nicosia, Cyprus", "value": "Nicosia"},
  {"text": "Nouakchott, Mauritania", "value": "Nouakchott"},
  {"text": "Noumea, New Caledonia", "value": "Noumea"},
  {"text": "Novosibirsk, Russia", "value": "Novosibirsk"},
  {"text": "Nuku'alofa, Tonga", "value": "Nuku'alofa"},
  {"text": "Nur-Sultan, Kazakhstan", "value": "Nur-Sultan"},
  {"text": "Nuuk, Greenland", "value": "Nuuk"},
  {"text": "Oranjestad, Aruba", "value": "Oranjestad"},
  {"text": "Osaka, Japan", "value": "Osaka"},
  {"text": "Oslo, Norway", "value": "Oslo"},
  {"text": "Ottawa, Canada", "value": "Ottawa"},
  {"text": "Ouagadougou, Burkina Faso", "value": "Ouagadougou"},
  {"text": "Pago Pago, American Samoa", "value": "Pago Pago"},
  {"text": "Palembang, Indonesia", "value": "Palembang"},
  {"text": "Palo Alto, United States", "value": "Palo Alto"},
  {"text": "Panama, Panama", "value": "Panama"},
  {"text": "Papeete, French Polynesia", "value": "Papeete"},
  {"text": "Paramaribo, Suriname", "value": "Paramaribo"},
  {"text": "Paris, France", "value": "Paris"},
  {"text": "Perth, Australia", "value": "Perth"},
  {"text": "Philadelphia, United States", "value": "Philadelphia"},
  {"text": "Phnom Penh, Cambodia", "value": "Phnom Penh"},
  {"text": "Phoenix, United States", "value": "Phoenix"},
  {"text": "Podgorica, Montenegro", "value": "Podgorica"},
  {"text": "Port Louis, Mauritius", "value": "Port Louis"},
  {"text": "Port Moresby, Papua New Guinea", "value": "Port Moresby"},
  {"text": "Port of Spain, Trinidad and Tobago", "value": "Port of Spain"},
  {"text": "Port-Vila, Vanuatu", "value": "Port-Vila"},
  {"text": "Port-au-Prince, Haiti", "value": "Port-au-Prince"},
  {"text": "Porto Alegre, Brazil", "value": "Porto Alegre"},
  {"text": "Porto-Novo, Benin", "value": "Porto-Novo"},
  {"text": "Prague, Czechia", "value": "Prague"},
  {"text": "Praia, Cabo Verde", "value": "Praia"},
  {"text": "Pretoria, South Africa", "value": "Pretoria"},
  {"text": "Pristina, Kosovo", "value": "Pristina"},
  {"text": "Puebla, Mexico", "value": "Puebla"},
  {"text": "Pune, India", "value": "Pune"},
  {"text": "Pyongyang, North Korea", "value": "Pyongyang"},
  {"text": "Quezon City, Philippines", "value": "Quezon City"},
  {"text": "Quito, Ecuador", "value": "Quito"},
  {"text": "Rabat, Morocco", "value": "Rabat"},
  {"text": "Rawalpindi, Pakistan", "value": "Rawalpindi"},
  {"text": "Recife, Brazil", "value": "Recife"},
  {"text": "Reykjavik, Iceland", "value": "Reykjavik"},
  {"text": "Riga, Latvia", "value": "Riga"},
  {"text": "Rio de Janeiro, Brazil", "value": "Rio de Janeiro"},
  {"text": "Riyadh, Saudi Arabia", "value": "Riyadh"},
  {"text": "Road Town, British Virgin Islands", "value": "Road Town"},
  {"text": "Rome, Italy", "value": "Rome"},
  {"text": "Roseau, Dominica", "value": "Roseau"},
  {"text": "Saint George's, Grenada", "value": "Saint George's"},
  {"text": "Saint Helier, Jersey", "value": "Saint Helier"},
  {"text": "Saint John's, Antigua and Barbuda", "value": "Saint John's"},
  {"text": "Saint Peter Port, Guernsey", "value": "Saint Peter Port"},
  {"text": "Saint Petersburg, Russia", "value": "Saint Petersburg"},
  {"text": "Saint-Denis, Reunion", "value": "Saint-Denis"},
  {"text": "Saint-Pierre, Reunion", "value": "Saint-Pierre"},
  {"text": "Saipan, Northern Mariana Islands", "value": "Saipan"},
  {"text": "Salvador, Brazil", "value": "Salvador"},
  {"text": "San Antonio, United States", "value": "San Antonio"},
  {"text": "San Diego, United States", "value": "San Diego"},
  {"text": "San Francisco, United States", "value": "San Francisco"},
  {"text": "San Jose, United States", "value": "San Jose"},
  {"text": "San Juan, Argentina", "value": "San Juan"},
  {"text": "San Marino, United States", "value": "San Marino"},
  {"text": "San Salvador, El Salvador", "value": "San Salvador"},
  {"text": "Sanaa, Yemen", "value": "Sanaa"},
  {"text": "Santa Cruz de la Sierra, Bolivia", "value": "Santa Cruz de la Sierra"},
  {"text": "Santiago, Chile", "value": "Santiago"},
  {"text": "Santo Domingo, Dominican Republic", "value": "Santo Domingo"},
  {"text": "Sao Paulo, Brazil", "value": "Sao Paulo"},
  {"text": "Sao Tome, Sao Tome and Principe", "value": "Sao Tome"},
  {"text": "Sapporo, Japan", "value": "Sapporo"},
  {"text": "Sarajevo, Bosnia and Herzegovina", "value": "Sarajevo"},
  {"text": "Seattle, United States", "value": "Seattle"},
  {"text": "Semarang, Indonesia", "value": "Semarang"},
  {"text": "Seoul, South Korea", "value": "Seoul"},
  {"text": "Shanghai, China", "value": "Shanghai"},
  {"text": "Sharjah, United Arab Emirates", "value": "Sharjah"},
  {"text": "Shenzhen, China", "value": "Shenzhen"},
  {"text": "Singapore, Singapore", "value": "Singapore"},
  {"text": "Skopje, North Macedonia", "value": "Skopje"},
  {"text": "Sofia, Bulgaria", "value": "Sofia"},
  {"text": "South Tangerang, Indonesia", "value": "South Tangerang"},
  {"text": "Soweto, South Africa", "value": "Soweto"},
  {"text": "Stockholm, Sweden", "value": "Stockholm"},
  {"text": "Sucre, Bolivia", "value": "Sucre"},
  {"text": "Surabaya, Indonesia", "value": "Surabaya"},
  {"text": "Surat, India", "value": "Surat"},
  {"text": "Suva, Fiji", "value": "Suva"},
  {"text": "Sydney, Australia", "value": "Sydney"},
  {"text": "Tabriz, Iran", "value": "Tabriz"},
  {"text": "Taipei, Taiwan", "value": "Taipei"},
  {"text": "Tallinn, Estonia", "value": "Tallinn"},
  {"text": "Tangerang, Indonesia", "value": "Tangerang"},
  {"text": "Tarawa, Kiribati", "value": "Tarawa"},
  {"text": "Tashkent, Uzbekistan", "value": "Tashkent"},
  {"text": "Tbilisi, Georgia", "value": "Tbilisi"},
  {"text": "Tegucigalpa, Honduras", "value": "Tegucigalpa"},
  {"text": "Tehran, Iran", "value": "Tehran"},
  {"text": "Tel Aviv, Israel", "value": "Tel Aviv"},
  {"text": "Thimphu, Bhutan", "value": "Thimphu"},
  {"text": "Tianjin, China", "value": "Tianjin"},
  {"text": "Tijuana, Mexico", "value": "Tijuana"},
  {"text": "Tirana, Albania", "value": "Tirana"},
  {"text": "Tokyo, Japan", "value": "Tokyo"},
  {"text": "Toronto, Canada", "value": "Toronto"},
  {"text": "Torshavn, Faroe Islands", "value": "Torshavn"},
  {"text": "Tripoli, Libya", "value": "Tripoli"},
  {"text": "Tunis, Tunisia", "value": "Tunis"},
  {"text": "Ulan Bator, Mongolia", "value": "Ulan Bator"},
  {"text": "Vaduz, Liechtenstein", "value": "Vaduz"},
  {"text": "Valencia, Venezuela", "value": "Valencia"},
  {"text": "Valletta, Malta", "value": "Valletta"},
  {"text": "Vancouver, Canada", "value": "Vancouver"},
  {"text": "Victoria, Canada", "value": "Victoria"},
  {"text": "Vienna, Austria", "value": "Vienna"},
  {"text": "Vientiane, Laos", "value": "Vientiane"},
  {"text": "Vilnius, Lithuania", "value": "Vilnius"},
  {"text": "Warsaw, Poland", "value": "Warsaw"},
  {"text": "Washington, United States", "value": "Washington"},
  {"text": "Wellington, New Zealand", "value": "Wellington"},
  {"text": "Willemstad, Curacao", "value": "Willemstad"},
  {"text": "Windhoek, Namibia", "value": "Windhoek"},
  {"text": "Wuhan, China", "value": "Wuhan"},
  {"text": "Xi'an, China", "value": "Xi'an"},
  {"text": "Yamoussoukro, Ivory Coast", "value": "Yamoussoukro"},
  {"text": "Yangon, Myanmar", "value": "Yangon"},
  {"text": "Yaounde, Cameroon", "value": "Yaounde"},
  {"text": "Yekaterinburg, Russia", "value": "Yekaterinburg"},
  {"text": "Yerevan, Armenia", "value": "Yerevan"},
  {"text": "Yokohama, Japan", "value": "Yokohama"},
  {"text": "Zagreb, Croatia", "value": "Zagreb"}
];
